# Generated by Django 5.0.7 on 2025-03-03 03:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('starting_addr', models.CharField(max_length=16)),
                ('curve_ball_speed', models.IntegerField(default=0)),
                ('fast_ball_speed', models.IntegerField(default=0)),
                ('curve', models.IntegerField(default=0)),
                ('fielding_arm', models.IntegerField(default=0)),
                ('batting_stance', models.IntegerField(default=0)),
                ('nice_contact_spot_size', models.IntegerField(default=0)),
                ('perfect_contact_spot_size', models.IntegerField(default=0)),
                ('slap_hit_power', models.IntegerField(default=0)),
                ('charge_hit_power', models.IntegerField(default=0)),
                ('bunting', models.IntegerField(default=0)),
                ('hit_trajectory_mpp', models.IntegerField(default=0)),
                ('hit_trajectory_mhl', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('throwing_arm', models.IntegerField(default=0)),
                ('character_class', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('captain', models.BooleanField(default=False)),
                ('captain_star_hit_or_pitch', models.IntegerField(default=0)),
                ('non_captain_star_swing', models.IntegerField(default=0)),
                ('non_captain_star_pitch', models.IntegerField(default=0)),
                ('batting_stat_bar', models.IntegerField(default=0)),
                ('pitching_stat_bar', models.IntegerField(default=0)),
                ('running_stat_bar', models.IntegerField(default=0)),
                ('fielding_stat_bar', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterChemistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_values', models.JSONField(default=dict)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility', to='api.character')),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('community_type', models.CharField(choices=[('official', 'Official'), ('unofficial', 'Unofficial')], max_length=16)),
                ('private', models.BooleanField(default=True)),
                ('active_tag_set_limit', models.IntegerField(default=5)),
                ('active_url', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_communities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'INVITED'), ('active', 'ACTIVE'), ('banned', 'BANNED')], default='invited', max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.role')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(related_name='communities', through='api.CommunityUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('tag_type', models.CharField(choices=[('component', 'Component'), ('competition', 'Competition'), ('community', 'Community'), ('client_code', 'Client Code'), ('gecko_code', 'Gecko Code'), ('test', 'Test')], db_index=True, max_length=16)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('gecko_code', models.TextField(blank=True, null=True)),
                ('gecko_code_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.community')),
            ],
        ),
        migrations.CreateModel(
            name='TagSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('tagset_type', models.CharField(choices=[('season', 'Season'), ('league', 'League'), ('tournament', 'Tournament')], db_index=True, max_length=120)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.community')),
                ('tags', models.ManyToManyField(blank=True, to='api.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(unique=True)),
                ('date_time_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_time_end', models.DateTimeField(blank=True, null=True)),
                ('ranked', models.BooleanField(default=False)),
                ('netplay', models.BooleanField(default=True)),
                ('stadium_id', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('home_score', models.IntegerField(default=0)),
                ('innings_selected', models.IntegerField(default=3)),
                ('innings_played', models.IntegerField(default=3)),
                ('valid', models.BooleanField(default=True)),
                ('average_ping', models.IntegerField(default=0)),
                ('lag_spikes', models.IntegerField(default=0)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='pending', max_length=10)),
                ('current_inning', models.IntegerField(default=0)),
                ('current_half_inning', models.IntegerField(default=0)),
                ('current_away_stars', models.IntegerField(default=0)),
                ('current_home_stars', models.IntegerField(default=0)),
                ('current_outs', models.IntegerField(default=0)),
                ('current_runner_1b', models.BooleanField(default=False)),
                ('current_runner_2b', models.BooleanField(default=False)),
                ('current_runner_3b', models.BooleanField(default=False)),
                ('batter_roster_loc', models.IntegerField(default=0)),
                ('pitcher_roster_loc', models.IntegerField(default=0)),
                ('away_captain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_captain', to='api.character')),
                ('away_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to=settings.AUTH_USER_MODEL)),
                ('home_captain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_captain', to='api.character')),
                ('home_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to=settings.AUTH_USER_MODEL)),
                ('quitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quit_games', to=settings.AUTH_USER_MODEL)),
                ('tag_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tagset')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('key', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Key')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('pings_daily', models.IntegerField(default=1)),
                ('pings_weekly', models.IntegerField(default=7)),
                ('last_ping_date', models.DateTimeField(blank=True, null=True)),
                ('total_pings', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('sponsor_limit', models.IntegerField(default=0)),
                ('daily_limit', models.IntegerField(default=0)),
                ('weekly_limit', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['daily_limit'], name='api_usergro_daily_l_991081_idx'), models.Index(fields=['weekly_limit'], name='api_usergro_weekly__8a4534_idx'), models.Index(fields=['sponsor_limit'], name='api_usergro_sponsor_dce373_idx')],
            },
        ),
        migrations.CreateModel(
            name='GameRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster_location', models.IntegerField()),
                ('is_home_team', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.character')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='api.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game', 'roster_location', 'is_home_team')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_url', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('private', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_group', models.ManyToManyField(blank=True, to='api.usergroup')),
            ],
            options={
                'indexes': [models.Index(fields=['private'], name='api_userpro_private_11abf5_idx'), models.Index(fields=['verified'], name='api_userpro_verifie_04431b_idx')],
            },
        ),
    ]
