# Generated by Django 5.0.7 on 2024-07-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagset',
            name='tags',
            field=models.ManyToManyField(null=True, to='api.tag'),
        ),
        migrations.AlterField(
            model_name='character',
            name='captain',
            field=models.BooleanField(),
        ),
    ]
