# Generated by Django 5.0.7 on 2025-03-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Key'),
        ),
    ]
