# Generated by Django 5.0.7 on 2024-07-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='comm_type',
            new_name='community_type',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='desc',
            new_name='description',
        ),
    ]
