# Generated by Django 5.0.7 on 2025-03-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeckoCodeTag',
        ),
    ]
