# Generated by Django 5.0.7 on 2025-03-03 03:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEventSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(default=0)),
                ('roster_loc', models.IntegerField(default=0)),
                ('captain', models.BooleanField(default=False)),
                ('superstar', models.BooleanField(default=False)),
                ('fielding_hand', models.BooleanField(default=False)),
                ('batting_hand', models.BooleanField(default=False)),
                ('position_stats', models.JSONField(default=dict)),
                ('offensive_stats', models.JSONField(default=dict)),
                ('defensive_stats', models.JSONField(default=dict)),
                ('runner_stats', models.JSONField(default=dict)),
                ('fielding_stats', models.JSONField(default=dict)),
                ('contact_stats', models.JSONField(default=dict)),
                ('pitch_stats', models.JSONField(default=dict)),
                ('star_stats', models.JSONField(default=dict)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.character')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_num', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('home_score', models.IntegerField(default=0)),
                ('inning', models.IntegerField(default=0)),
                ('half_inning', models.IntegerField(default=0)),
                ('chem_links_ob', models.IntegerField(default=0)),
                ('star_chance', models.IntegerField(default=0)),
                ('away_stars', models.IntegerField(default=0)),
                ('home_stars', models.IntegerField(default=0)),
                ('pitcher_stamina', models.IntegerField(default=0)),
                ('outs', models.IntegerField(default=0)),
                ('balls', models.IntegerField(default=0)),
                ('strikes', models.IntegerField(default=0)),
                ('result_num_of_outs', models.IntegerField(default=0)),
                ('result_rbi', models.IntegerField(default=0)),
                ('result_of_ab', models.IntegerField(default=0)),
                ('winner_score', models.IntegerField(default=0)),
                ('loser_score', models.IntegerField(default=0)),
                ('winner_elo', models.IntegerField(default=0)),
                ('loser_elo', models.IntegerField(default=0)),
                ('winner_accept', models.BooleanField(default=True)),
                ('loser_accept', models.BooleanField(null=True)),
                ('admin_accept', models.BooleanField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('loser_comm_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loser_comm_user', to='api.communityuser')),
                ('winner_comm_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_comm_user', to='api.communityuser')),
                ('batter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_batter', to='api.gameeventsummary')),
                ('catcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_catcher', to='api.gameeventsummary')),
                ('pitcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_pitcher', to='api.gameeventsummary')),
                ('runners', models.ManyToManyField(related_name='event_runners', to='api.gameeventsummary')),
            ],
        ),
        migrations.CreateModel(
            name='Ladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_searching', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField(default=0)),
                ('rd', models.IntegerField(default=0)),
                ('vol', models.FloatField(default=0.0)),
                ('tag_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tagset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tag_set', 'user')},
            },
        ),
    ]
