# Generated by Django 5.0.7 on 2025-03-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_geckocodetag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
