# Generated by Django 5.0.7 on 2024-07-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tagset_tags_alter_character_captain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagset',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.tag'),
        ),
    ]
