# Generated by Django 5.0.7 on 2024-07-27 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_characterpositionsummary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('action', models.IntegerField()),
                ('jump', models.IntegerField()),
                ('bobble', models.IntegerField()),
                ('swap', models.BooleanField()),
                ('manual_select', models.IntegerField()),
                ('fielder_x_pos', models.FloatField()),
                ('fielder_y_pos', models.FloatField()),
                ('fielder_z_pos', models.FloatField()),
                ('fielder_character_game_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.charactergamesummary')),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_base', models.IntegerField()),
                ('result_base', models.IntegerField()),
                ('out_type', models.IntegerField()),
                ('out_location', models.IntegerField()),
                ('steal', models.IntegerField()),
                ('runner_character_game_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.charactergamesummary')),
            ],
        ),
    ]
