# Generated by Django 5.0.7 on 2025-03-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gameeventsummary_gameevent_ladder'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tagset',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
