# Generated by Django 5.0.7 on 2024-07-27 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fieldingsummary_runner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_contact', models.IntegerField()),
                ('charge_power_up', models.FloatField()),
                ('charge_power_down', models.FloatField()),
                ('star_swing_five_star', models.IntegerField()),
                ('input_direction', models.IntegerField()),
                ('input_direction_stick', models.IntegerField()),
                ('frame_of_swing_upon_contact', models.IntegerField()),
                ('ball_power', models.IntegerField()),
                ('ball_horiz_angle', models.IntegerField()),
                ('ball_vert_angle', models.IntegerField()),
                ('contact_absolute', models.FloatField()),
                ('contact_quality', models.FloatField()),
                ('rng1', models.FloatField()),
                ('rng2', models.FloatField()),
                ('rng3', models.FloatField()),
                ('ball_x_velocity', models.FloatField()),
                ('ball_y_velocity', models.FloatField()),
                ('ball_z_velocity', models.FloatField()),
                ('ball_x_contact_pos', models.FloatField()),
                ('ball_z_contact_pos', models.FloatField()),
                ('ball_x_landing_pos', models.FloatField()),
                ('ball_y_landing_pos', models.FloatField()),
                ('ball_z_landing_pos', models.FloatField()),
                ('ball_max_height', models.FloatField()),
                ('ball_hang_time', models.FloatField()),
                ('primary_result', models.IntegerField()),
                ('secondary_result', models.IntegerField()),
                ('fielding_summary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fieldingsummary')),
            ],
        ),
        migrations.CreateModel(
            name='PitchSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_type', models.IntegerField()),
                ('charge_pitch_type', models.IntegerField()),
                ('star_pitch', models.IntegerField()),
                ('pitch_speed', models.IntegerField()),
                ('d_ball', models.BooleanField()),
                ('type_of_swing', models.IntegerField()),
                ('ball_position_strikezone', models.IntegerField()),
                ('in_strikezone', models.BooleanField()),
                ('bat_x_contact_pos', models.FloatField()),
                ('bat_z_contact_pos', models.FloatField()),
                ('contact_summary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contactsummary')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_num', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('home_score', models.IntegerField()),
                ('inning', models.IntegerField()),
                ('half_inning', models.IntegerField()),
                ('chem_links_ob', models.IntegerField()),
                ('star_chance', models.IntegerField()),
                ('away_stars', models.IntegerField()),
                ('home_stars', models.IntegerField()),
                ('pitcher_stamina', models.IntegerField()),
                ('outs', models.IntegerField()),
                ('balls', models.IntegerField()),
                ('strikes', models.IntegerField()),
                ('result_num_of_outs', models.IntegerField()),
                ('result_rbi', models.IntegerField()),
                ('result_of_ab', models.IntegerField()),
                ('batter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_batter', to='api.charactergamesummary')),
                ('catcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_catcher', to='api.charactergamesummary')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('pitcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_pitcher', to='api.charactergamesummary')),
                ('runner_on_0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_runner_0', to='api.runner')),
                ('runner_on_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_runner_1', to='api.runner')),
                ('runner_on_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_runner_2', to='api.runner')),
                ('runner_on_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_runner_3', to='api.runner')),
                ('pitch_summary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pitchsummary')),
            ],
        ),
    ]
