# Generated by Django 5.0.7 on 2025-02-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tag_gecko_code_tag_gecko_code_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
