# Generated by Django 5.0.7 on 2025-03-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tag_name_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='slug',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
