# Generated by Django 5.0.7 on 2024-07-27 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contactsummary_pitchsummary_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('tag_type', models.CharField(max_length=16)),
                ('desc', models.CharField(max_length=300)),
                ('active', models.BooleanField()),
                ('date_created', models.IntegerField()),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.community')),
            ],
        ),
    ]
