# Generated by Django 5.0.7 on 2025-02-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tag_last_modified_alter_tag_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
