# Generated by Django 5.0.7 on 2025-03-09 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_permission_role_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='characterchemistry',
            options={'ordering': ['character']},
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='communityuser',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['community', 'name']},
        ),
        migrations.AlterModelOptions(
            name='tagset',
            options={'ordering': ['community', 'name']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user']},
        ),
    ]
