# Generated by Django 5.0.7 on 2024-07-27 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeckoCodeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gecko_code_desc', models.TextField()),
                ('gecko_code', models.TextField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Ladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_searching', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('rd', models.IntegerField()),
                ('vol', models.FloatField()),
                ('community_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.communityuser')),
                ('tag_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tagset')),
            ],
        ),
    ]
