# Generated by Django 5.0.7 on 2024-07-27 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_geckocodetag_ladder'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_score', models.IntegerField()),
                ('loser_score', models.IntegerField()),
                ('winner_elo', models.IntegerField()),
                ('loser_elo', models.IntegerField()),
                ('winner_accept', models.BooleanField()),
                ('loser_accept', models.BooleanField(null=True)),
                ('admin_accept', models.BooleanField(null=True)),
                ('date_created', models.IntegerField(null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('loser_comm_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser_comm_user', to='api.communityuser')),
                ('tag_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tagset')),
                ('winner_comm_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_comm_user', to='api.communityuser')),
            ],
        ),
    ]
