# Generated by Django 5.0.7 on 2024-07-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_gamehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riouser',
            name='date_created',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
