# Generated by Django 5.0.7 on 2024-07-27 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_riouser_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riouser',
            name='active_url',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='riouser',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.apikey'),
        ),
        migrations.AlterField(
            model_name='riouser',
            name='rio_key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
