# Generated by Django 5.0.7 on 2024-07-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_riouser_active_url_alter_riouser_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riouser',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='riouser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
