from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class ApiKey(models.Model):
    api_key = models.CharField(max_length=50, unique=True)
    date_created = models.DateTimeField(auto_created=True, auto_now=True)
    pings_daily = models.IntegerField()
    pings_weekly = models.IntegerField()
    last_ping_date = models.IntegerField()
    total_pings = models.IntegerField()

    def __str__(self):
        return self.api_key


class ChemistryTable(models.Model):
    # Not needed as Django creates an ID field automatically
    # id = db.Column(db.Integer, primary_key=True)
    mario = models.IntegerField()
    luigi = models.IntegerField()
    dk = models.IntegerField()
    diddy = models.IntegerField()
    peach = models.IntegerField()
    daisy = models.IntegerField()
    yoshi = models.IntegerField()
    baby_mario = models.IntegerField()
    baby_luigi = models.IntegerField()
    bowser = models.IntegerField()
    wario = models.IntegerField()
    waluigi = models.IntegerField()
    koopa_r = models.IntegerField()
    toad_r = models.IntegerField()
    boo = models.IntegerField()
    toadette = models.IntegerField()
    shy_guy_r = models.IntegerField()
    birdo = models.IntegerField()
    monty = models.IntegerField()
    bowser_jr = models.IntegerField()
    paratroopa_r = models.IntegerField()
    pianta_b = models.IntegerField()
    pianta_r = models.IntegerField()
    pianta_y = models.IntegerField()
    noki_b = models.IntegerField()
    noki_r = models.IntegerField()
    noki_g = models.IntegerField()
    bro_h = models.IntegerField()
    toadsworth = models.IntegerField()
    toad_b = models.IntegerField()
    toad_y = models.IntegerField()
    toad_g = models.IntegerField()
    toad_p = models.IntegerField()
    magikoopa_b = models.IntegerField()
    magikoopa_r = models.IntegerField()
    magikoopa_g = models.IntegerField()
    magikoopa_y = models.IntegerField()
    king_boo = models.IntegerField()
    petey = models.IntegerField()
    dixie = models.IntegerField()
    goomba = models.IntegerField()
    paragoomba = models.IntegerField()
    koopa_g = models.IntegerField()
    paratroopa_g = models.IntegerField()
    shy_guy_b = models.IntegerField()
    shy_guy_y = models.IntegerField()
    shy_guy_g = models.IntegerField()
    shy_guy_bk = models.IntegerField()
    dry_bones_gy = models.IntegerField()
    dry_bones_g = models.IntegerField()
    dry_bones_r = models.IntegerField()
    dry_bones_b = models.IntegerField()
    bro_f = models.IntegerField()
    bro_b = models.IntegerField()


class Character(models.Model):
    char_id = models.IntegerField(primary_key=True)
    chemistry_table = models.ForeignKey(ChemistryTable, on_delete=models.CASCADE, null=False)
    name = models.CharField(max_length=16)
    starting_addr = models.CharField(max_length=16)
    curve_ball_speed = models.IntegerField()
    fast_ball_speed = models.IntegerField()
    curve = models.IntegerField()
    fielding_arm = models.IntegerField()
    batting_stance = models.IntegerField()
    nice_contact_spot_size = models.IntegerField()
    perfect_contact_spot_size = models.IntegerField()
    slap_hit_power = models.IntegerField()
    charge_hit_power = models.IntegerField()
    bunting = models.IntegerField()
    hit_trajectory_mpp = models.IntegerField()
    hit_trajectory_mhl = models.IntegerField()
    speed = models.IntegerField()
    throwing_arm = models.IntegerField()
    character_class = models.IntegerField()
    weight = models.IntegerField()
    captain = models.BooleanField()
    captain_star_hit_or_pitch = models.IntegerField()
    non_captain_star_swing = models.IntegerField()
    non_captain_star_pitch = models.IntegerField()
    batting_stat_bar = models.IntegerField()
    pitching_stat_bar = models.IntegerField()
    running_stat_bar = models.IntegerField()
    fielding_stat_bar = models.IntegerField()


class UserGroup(models.Model):
    daily_limit = models.IntegerField()
    weekly_limit = models.IntegerField()
    sponsor_limit = models.IntegerField()
    name = models.CharField(max_length=32, unique=True)
    desc = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class RioUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    api_key = models.ForeignKey(ApiKey, blank=True, null=True, on_delete=models.CASCADE)
    user_group = models.ManyToManyField(UserGroup, blank=True)
    rio_key = models.CharField(max_length=50, unique=True, blank=True, null=True)
    active_url = models.CharField(max_length=50, unique=True, blank=True, null=True)
    private = models.BooleanField(default=False)
    verified = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_created=True, auto_now=True)

    def __str__(self):
        return self.user.username

    def username(self):
        return self.user.username


class Community(models.Model):
    name = models.CharField(max_length=32, unique=True)
    sponsor = models.ForeignKey(RioUser, null=True, on_delete=models.CASCADE)
    comm_type = models.CharField(max_length=16)
    private = models.BooleanField()
    active_tag_set_limit = models.IntegerField()
    active_url = models.CharField(max_length=50, unique=True)
    desc = models.CharField(max_length=300)
    date_created = models.IntegerField()


class CommunityUser(models.Model):
    user = models.ForeignKey(RioUser, null=False, on_delete=models.CASCADE)
    community = models.ForeignKey(Community, null=False, on_delete=models.CASCADE)
    admin = models.BooleanField()
    invited = models.BooleanField()
    active = models.BooleanField()
    banned = models.BooleanField()
    date_joined = models.IntegerField()


class Tag(models.Model):
    community = models.ForeignKey(Community, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=32, unique=True)
    tag_type = models.CharField(max_length=16)
    desc = models.CharField(max_length=300)
    active = models.BooleanField()
    date_created = models.IntegerField()


class TagSet(models.Model):
    community = models.ForeignKey(Community, null=True, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)
    name = models.CharField(max_length=120, unique=True)
    type = models.CharField(max_length=120)  # Season, league, tournament.
    start_date = models.IntegerField()
    end_date = models.IntegerField()


class GeckoCodeTag(models.Model):
    tag = models.ForeignKey(Tag, null=False, on_delete=models.CASCADE)
    gecko_code_desc = models.TextField()
    gecko_code = models.TextField()


class OngoingGame(models.Model):
    date_time_start = models.IntegerField()
    stadium_id = models.IntegerField()
    away_player = models.ForeignKey(RioUser, null=False, on_delete=models.CASCADE, related_name='ongoing_away_player')
    home_player = models.ForeignKey(RioUser, null=False, on_delete=models.CASCADE, related_name='ongoing_home_player')
    tag_set = models.ForeignKey(TagSet, null=False, on_delete=models.CASCADE)
    away_captain = models.IntegerField()
    home_captain = models.IntegerField()
    away_roster_0_char = models.ForeignKey(Character, null=False, on_delete=models.CASCADE, related_name='away_roster_0_char')
    away_roster_1_char = models.ForeignKey(Character, null=False, on_delete=models.CASCADE, related_name='away_roster_1_char')
    away_roster_2_char = models.ForeignKey(Character, null=False, on_delete=models.CASCADE, related_name='away_roster_2_char')
    away_roster_3_char = models.ForeignKey(Character, null=False, on_delete=models.CASCADE, related_name='away_roster_3_char')
    away_roster_4_char = models.ForeignKey(Character, null=False, on_delete=models.CASCADE, related_name='away_roster_4_char')
    away_roster_5_char = models.ForeignKey(Character, null=False, on_delete=models.CASCADE, related_name='away_roster_5_char')
    away_roster_6_char = models.ForeignKey(Character, null=False, on_delete=models.CASCADE, related_name='away_roster_6_char')
    away_roster_7_char = models.ForeignKey(Character, null=False, on_delete=models.CASCADE, related_name='away_roster_7_char')
    away_roster_8_char = models.ForeignKey(Character, null=False, on_delete=models.CASCADE, related_name='away_roster_8_char')
    home_roster_0_char = models.ForeignKey(Character, null=False, on_delete=models.CASCADE, related_name='home_roster_0_char')
    home_roster_1_char = models.ForeignKey(Character, null=False, on_delete=models.CASCADE, related_name='home_roster_1_char')
    home_roster_2_char = models.ForeignKey(Character, null=False, on_delete=models.CASCADE, related_name='home_roster_2_char')
    home_roster_3_char = models.ForeignKey(Character, null=False, on_delete=models.CASCADE, related_name='home_roster_3_char')
    home_roster_4_char = models.ForeignKey(Character, null=False, on_delete=models.CASCADE, related_name='home_roster_4_char')
    home_roster_5_char = models.ForeignKey(Character, null=False, on_delete=models.CASCADE, related_name='home_roster_5_char')
    home_roster_6_char = models.ForeignKey(Character, null=False, on_delete=models.CASCADE, related_name='home_roster_6_char')
    home_roster_7_char = models.ForeignKey(Character, null=False, on_delete=models.CASCADE, related_name='home_roster_7_char')
    home_roster_8_char = models.ForeignKey(Character, null=False, on_delete=models.CASCADE, related_name='home_roster_8_char')
    current_inning = models.IntegerField()
    current_half_inning = models.IntegerField()
    current_away_score = models.IntegerField()
    current_home_score = models.IntegerField()
    current_away_stars = models.IntegerField()
    current_home_stars = models.IntegerField()
    current_outs = models.IntegerField()
    current_runner_1b = models.BooleanField()
    current_runner_2b = models.BooleanField()
    current_runner_3b = models.BooleanField()
    batter_roster_loc = models.IntegerField()
    pitcher_roster_loc = models.IntegerField()


class Game(models.Model):
    away_player = models.ForeignKey(RioUser, null=False, on_delete=models.CASCADE, related_name='game_away_player')
    home_player = models.ForeignKey(RioUser, null=False, on_delete=models.CASCADE, related_name='game_home_player')
    date_time_start = models.IntegerField()
    date_time_end = models.IntegerField()
    ranked = models.BooleanField()
    netplay = models.BooleanField()
    stadium_id = models.IntegerField()
    away_score = models.IntegerField()
    home_score = models.IntegerField()
    innings_selected = models.IntegerField()
    innings_played = models.IntegerField()
    quitter = models.IntegerField()  # 0=None, 1=Away, 2=Home
    valid = models.BooleanField()
    average_ping = models.IntegerField()
    lag_spikes = models.IntegerField()
    version = models.CharField(max_length=50)


class CharacterPositionSummary(models.Model):
    pitches_at_p = models.IntegerField()
    pitches_at_c = models.IntegerField()
    pitches_at_1b = models.IntegerField()
    pitches_at_2b = models.IntegerField()
    pitches_at_3b = models.IntegerField()
    pitches_at_ss = models.IntegerField()
    pitches_at_lf = models.IntegerField()
    pitches_at_cf = models.IntegerField()
    pitches_at_rf = models.IntegerField()
    batter_outs_at_p = models.IntegerField()
    batter_outs_at_c = models.IntegerField()
    batter_outs_at_1b = models.IntegerField()
    batter_outs_at_2b = models.IntegerField()
    batter_outs_at_3b = models.IntegerField()
    batter_outs_at_ss = models.IntegerField()
    batter_outs_at_lf = models.IntegerField()
    batter_outs_at_cf = models.IntegerField()
    batter_outs_at_rf = models.IntegerField()
    outs_at_p = models.IntegerField()
    outs_at_c = models.IntegerField()
    outs_at_1b = models.IntegerField()
    outs_at_2b = models.IntegerField()
    outs_at_3b = models.IntegerField()
    outs_at_ss = models.IntegerField()
    outs_at_lf = models.IntegerField()
    outs_at_cf = models.IntegerField()
    outs_at_rf = models.IntegerField()


class CharacterGameSummary(models.Model):
    game = models.ForeignKey(Game, null=False, on_delete=models.CASCADE)
    char = models.ForeignKey(Character, null=False, on_delete=models.CASCADE)
    user = models.ForeignKey(RioUser, null=False, on_delete=models.CASCADE)
    character_position_summary = models.ForeignKey(CharacterPositionSummary, null=False, on_delete=models.CASCADE)
    team_id = models.IntegerField()
    roster_loc = models.IntegerField()  # 0-8
    captain = models.BooleanField()
    superstar = models.BooleanField()
    fielding_hand = models.BooleanField()
    batting_hand = models.BooleanField()
    #Defensive Stats
    batters_faced = models.IntegerField()
    runs_allowed = models.IntegerField()
    earned_runs = models.IntegerField()
    batters_walked = models.IntegerField()
    batters_hit = models.IntegerField()
    hits_allowed = models.IntegerField()
    homeruns_allowed = models.IntegerField()
    pitches_thrown = models.IntegerField()
    stamina = models.IntegerField()
    was_pitcher = models.IntegerField()
    strikeouts_pitched = models.IntegerField()
    star_pitches_thrown = models.IntegerField()
    big_plays = models.IntegerField()
    outs_pitched = models.IntegerField()
    #Offensive Stats
    at_bats = models.IntegerField()
    plate_appearances = models.IntegerField()
    hits = models.IntegerField()
    singles = models.IntegerField()
    doubles = models.IntegerField()
    triples = models.IntegerField()
    homeruns = models.IntegerField()
    successful_bunts = models.IntegerField()
    sac_flys = models.IntegerField()
    strikeouts = models.IntegerField()
    walks_bb = models.IntegerField()
    walks_hit = models.IntegerField()
    rbi = models.IntegerField()
    bases_stolen = models.IntegerField()
    star_hits = models.IntegerField()
    #Star tracking (Not in JSON. Calculated in populate_db)
    offensive_star_swings = models.IntegerField()
    offensive_stars_used = models.IntegerField()
    offensive_stars_put_in_play = models.IntegerField()
    offensive_star_successes = models.IntegerField()
    offensive_star_chances = models.IntegerField()
    offensive_star_chances_won = models.IntegerField()
    defensive_star_pitches = models.IntegerField()
    defensive_stars_used = models.IntegerField()
    defensive_star_successes = models.IntegerField()
    defensive_star_chances = models.IntegerField()
    defensive_star_chances_won = models.IntegerField()


class Runner(models.Model):
    runner_character_game_summary = models.ForeignKey(CharacterGameSummary, null=False, on_delete=models.CASCADE)
    initial_base = models.IntegerField()
    result_base = models.IntegerField()
    out_type = models.IntegerField()
    out_location = models.IntegerField()
    steal = models.IntegerField()


class FieldingSummary(models.Model):
    fielder_character_game_summary = models.ForeignKey(CharacterGameSummary, null=False, on_delete=models.CASCADE)
    position = models.IntegerField()
    action = models.IntegerField()
    jump = models.IntegerField()
    bobble = models.IntegerField()
    swap = models.BooleanField()
    manual_select = models.IntegerField()
    fielder_x_pos = models.FloatField()
    fielder_y_pos = models.FloatField()
    fielder_z_pos = models.FloatField()


class ContactSummary(models.Model):
    fielding_summary = models.ForeignKey(FieldingSummary, null=True, on_delete=models.CASCADE)
    type_of_contact = models.IntegerField()
    charge_power_up = models.FloatField()
    charge_power_down = models.FloatField()
    star_swing_five_star = models.IntegerField()
    input_direction = models.IntegerField()
    input_direction_stick = models.IntegerField()
    frame_of_swing_upon_contact = models.IntegerField()
    ball_power = models.IntegerField()
    ball_horiz_angle = models.IntegerField()
    ball_vert_angle = models.IntegerField()
    contact_absolute = models.FloatField()
    contact_quality = models.FloatField()
    rng1 = models.FloatField()
    rng2 = models.FloatField()
    rng3 = models.FloatField()
    ball_x_velocity = models.FloatField()
    ball_y_velocity = models.FloatField()
    ball_z_velocity = models.FloatField()
    ball_x_contact_pos = models.FloatField()
    ball_z_contact_pos = models.FloatField()
    ball_x_landing_pos = models.FloatField()
    ball_y_landing_pos = models.FloatField()
    ball_z_landing_pos = models.FloatField()
    ball_max_height = models.FloatField()
    ball_hang_time = models.FloatField()
    primary_result = models.IntegerField()
    secondary_result = models.IntegerField()


class PitchSummary(models.Model):
    contact_summary = models.ForeignKey(ContactSummary, null=True, on_delete=models.CASCADE)
    pitch_type = models.IntegerField()
    charge_pitch_type = models.IntegerField()
    star_pitch = models.IntegerField()
    pitch_speed = models.IntegerField()
    d_ball = models.BooleanField()
    type_of_swing = models.IntegerField()
    ball_position_strikezone = models.IntegerField()
    in_strikezone = models.BooleanField()
    bat_x_contact_pos = models.FloatField()
    bat_z_contact_pos = models.FloatField()


class Event(models.Model):
    game = models.ForeignKey(Game, null=False, on_delete=models.CASCADE)
    pitcher = models.ForeignKey(CharacterGameSummary, null=False, on_delete=models.CASCADE, related_name='event_pitcher')  # Based on "Pitcher Roster Loc" in JSON
    batter = models.ForeignKey(CharacterGameSummary, null=False, on_delete=models.CASCADE, related_name='event_batter')
    catcher = models.ForeignKey(CharacterGameSummary, null=False, on_delete=models.CASCADE, related_name='event_catcher')
    runner_on_0 = models.ForeignKey(Runner, null=False, on_delete=models.CASCADE, related_name='event_runner_0')
    runner_on_1 = models.ForeignKey(Runner, null=False, on_delete=models.CASCADE, related_name='event_runner_1')
    runner_on_2 = models.ForeignKey(Runner, null=False, on_delete=models.CASCADE, related_name='event_runner_2')
    runner_on_3 = models.ForeignKey(Runner, null=False, on_delete=models.CASCADE, related_name='event_runner_3')
    pitch_summary = models.ForeignKey(PitchSummary, null=True, on_delete=models.CASCADE)
    event_num = models.IntegerField()
    away_score = models.IntegerField()
    home_score = models.IntegerField()
    inning = models.IntegerField()
    half_inning = models.IntegerField()
    chem_links_ob = models.IntegerField()
    star_chance = models.IntegerField()
    away_stars = models.IntegerField()
    home_stars = models.IntegerField()
    pitcher_stamina = models.IntegerField()
    outs = models.IntegerField()
    balls = models.IntegerField()
    strikes = models.IntegerField()
    result_num_of_outs = models.IntegerField()
    result_rbi = models.IntegerField()
    result_of_ab = models.IntegerField()


class Ladder(models.Model):
    tag_set = models.ForeignKey(TagSet, null=False, on_delete=models.CASCADE)
    community_user = models.ForeignKey(CommunityUser, null=False, on_delete=models.CASCADE)
    started_searching = models.IntegerField()
    rating = models.IntegerField()
    rd = models.IntegerField()
    vol = models.FloatField()


class GameHistory(models.Model):
    game = models.ForeignKey(Game, null=True, on_delete=models.CASCADE)
    tag_set = models.ForeignKey(TagSet, null=False, on_delete=models.CASCADE)
    winner_comm_user = models.ForeignKey(CommunityUser, null=False, on_delete=models.CASCADE, related_name='winner_comm_user')
    loser_comm_user = models.ForeignKey(CommunityUser, null=False, on_delete=models.CASCADE, related_name='loser_comm_user')
    winner_score = models.IntegerField()
    loser_score = models.IntegerField()
    winner_elo = models.IntegerField()
    loser_elo = models.IntegerField()
    winner_accept = models.BooleanField()
    loser_accept = models.BooleanField(null=True)
    admin_accept = models.BooleanField(null=True)
    date_created = models.IntegerField(null=True)
